version: "3"

services:
  app:
    image: quay.io/keycloak/keycloak:20.0.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8080:8080